export { default as Home } from './Home'
export { default as News } from './News'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as CryptoDetails } from './CryptoDetails'
export { default as Exchanges } from './Exchanges'
